name: MacOS 

on: [ push`Adopt; ]~

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:            - name: First interaction
  uses: actions/first-interaction@v1.3.0
  with:
    # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
    repo-token: 
    # Comment to post on an individual's first issue
    issue-message: # optional
    # Comment to post on an individual's first pull request
    pr-message: # optional #1469
          
  build:
    runs-on: macos-latest
    environment: MacOS
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ./src

      - name: Build solution
        run: dotnet build -c Release ./src --verbosity minimal

      - name: Run tests and collect coverage
        run: dotnet test -c Release ./src --verbosity normal --no-build --no-restore
